[package]
name = "dual-kawase-demo"
version = "0.1.2"
authors = ["Bernd Busse <bernd AT busse-apps DOT de>"]
edition = "2018"

[dependencies]
cpu-time = "1.0"
sdl2 = { version = "0.32", features = ["gfx"] }
gl = "0.14"
glyph_brush = "0.6"
image = { version = "0.22", features = ["jpeg", "png"] }
